apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rsyncpopulators.kvm.io
spec:
  group: kvm.io
  names:
    kind: RsyncPopulator
    listKind: RsyncPopulatorList
    plural: rsyncpopulators
    singular: rsyncpopulator
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          spec:
            properties:
              username:
                type: string
              password:
                type: string
              path:
                type: string
              service:
                type: string
            required:
            - username
            - password
            - path
            - service
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
