apiVersion: v1
kind: ServiceAccount
metadata:
  name: rsync-populator
  namespace: volume-copy
  labels:
    demo.io/name: rsync-populator
    demo.io/role: volume-populator 
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rsync-populator
  labels:
    demo.io/name: rsync-populator
    demo.io/role: volume-populator 
rules:
  - apiGroups: [""]
    resources: [persistentvolumes]
    verbs: [get, list, watch, patch]
  - apiGroups: [""]
    resources: [persistentvolumeclaims]
    verbs: [get, list, watch, patch, create, delete]
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, watch, create, delete]
  - apiGroups: [storage.k8s.io]
    resources: [storageclasses]
    verbs: [get, list, watch]

  - apiGroups: [demo.io]
    resources: [rsyncpopulators]
    verbs: [get, list, watch]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rsync-populator
  labels:
    demo.io/name: rsync-populator
    demo.io/role: volume-populator 
subjects:
  - kind: ServiceAccount
    name: rsync-populator
    namespace: volume-copy
roleRef:
  kind: ClusterRole
  name: rsync-populator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rsync-populator
  namespace: volume-copy
  labels:
    demo.io/app: rsync-populator
    demo.io/name: rsync-populator
    demo.io/role: volume-populator 
spec:
  serviceName: rsync-populator
  replicas: 1
  selector:
    matchLabels:
      demo.io/app: rsync-populator
      demo.io/name: rsync-populator
      demo.io/role: volume-populator
  template:
    metadata:
      labels:
        demo.io/app: rsync-populator
        demo.io/name: rsync-populator
        demo.io/role: volume-populator
    spec:
      serviceAccount: rsync-populator
      containers:
      - name: rsync-populator
        image: ghcr.io/shovanmaity/rsync-populator:latest
        imagePullPolicy: Always
        command:
        - rsync-populator
        args:
        - --v=2
        - --image-name=ghcr.io/shovanmaity/rsync-client:latest
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
