apiVersion: v1
kind: Pod
metadata:
  name: block-volume
spec:
  containers:
  - name: block-volume
    image: busybox
    command:
    - sleep
    - "24h"
    volumeDevices:
    - name: data
      devicePath: /dev/block
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: block-pvc
