apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-dash
spec:
  dataSource:
    apiGroup: example.io
    kind: RsyncPopulator
    name: rsync-populator-1
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
