apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: volumeclaimpopulators.kvm.io
spec:
  group: kvm.io
  names:
    kind: VolumeClaimPopulator
    listKind: VolumeClaimPopulatorList
    plural: volumeclaimpopulators
    singular: volumeclaimpopulator
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          spec:
            properties:
              name:
                type: string
            required:
            - name
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
