apiVersion: v1
kind: Pod
metadata:
  name: fsgroup-volume
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 5000
  containers:
  - name: fsgroup-volume
    image: busybox
    command:
    - sleep
    - "24h"
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: fsgroup-pvc
