apiVersion: v1
kind: Pod
metadata:
  name: fs-volume
spec:
  containers:
  - name: fs-volume
    image: busybox
    command:
    - sleep
    - "24h"
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: fs-pvc
