apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  #storageClassName: my-sc
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi