apiVersion: v1
kind: Namespace
metadata:
  name: volume-copy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: volume-rename
  namespace: volume-copy
  labels:
    demo.io/name: volume-rename
    demo.io/role: volume-populator 
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: volume-rename
  labels:
    demo.io/name: volume-rename
    demo.io/role: volume-populator 
rules:
  - apiGroups: [""]
    resources: [persistentvolumeclaims]
    verbs: [get, create]

  - apiGroups: [demo.io]
    resources: [persistentvolumepopulators]
    verbs: [get, delete, create]
  - apiGroups: [demo.io]
    resources: [volumerenames]
    verbs: [get, watch, list, update]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: volume-rename
  labels:
    demo.io/name: volume-rename
    demo.io/role: volume-populator 
subjects:
  - kind: ServiceAccount
    name: volume-rename
    namespace: volume-copy
roleRef:
  kind: ClusterRole
  name: volume-rename
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: volume-rename
  namespace: volume-copy
  labels:
    demo.io/app: volume-rename
    demo.io/name: volume-rename
    demo.io/role: volume-populator 
spec:
  serviceName: volume-rename
  replicas: 1
  selector:
    matchLabels:
      demo.io/app: volume-rename
      demo.io/name: volume-rename
      demo.io/role: volume-populator
  template:
    metadata:
      labels:
        demo.io/app: volume-rename
        demo.io/name: volume-rename
        demo.io/role: volume-populator
    spec:
      serviceAccount: volume-rename
      containers:
      - name: volume-rename
        image: quay.io/k8s-volume-copy/volume-rename:ci
        imagePullPolicy: Always
        command:
        - volume-rename
        args:
        - --v=2
