apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: my-pvc
  containers:
  - name: demo
    image: busybox
    command: [ "sh", "-c", "sleep 24h" ]
    volumeMounts:
    - name: data
      mountPath: /data