apiVersion: v1
kind: Namespace
metadata:
  name: volume-migration
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rsync-populator
  namespace: volume-migration
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rsync-populator
rules:
  - apiGroups: [""]
    resources: [persistentvolumes]
    verbs: [get, list, watch, patch]
  - apiGroups: [""]
    resources: [persistentvolumeclaims]
    verbs: [get, list, watch, patch, create, delete]
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, watch, create, delete]
  - apiGroups: [storage.k8s.io]
    resources: [storageclasses]
    verbs: [get, list, watch]

  - apiGroups: [example.io]
    resources: [rsyncpopulators]
    verbs: [get, list, watch]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rsync-populator
subjects:
  - kind: ServiceAccount
    name: rsync-populator
    namespace: volume-migration
roleRef:
  kind: ClusterRole
  name: rsync-populator
  apiGroup: rbac.authorization.k8s.io
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: rsync-populator
  namespace: volume-migration
spec:
  selector:
    matchLabels:
      app: rsync-populator
  template:
    metadata:
      labels:
        app: rsync-populator
    spec:
      serviceAccount: rsync-populator
      containers:
        - name: rsync-populator
          image: quay.io/shovanmaity/rsyncp:latest
          imagePullPolicy: Always
          command:
          - rsyncp
          args:
          - --image-name=quay.io/shovanmaity/rsync:latest
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
