apiVersion: v1
kind: Pod
metadata:
  name: rsync-client
  labels:
    role: rsync-client
    name: rsync-client
spec:
  containers:
  - name: rsync-client
    image: quay.io/k8s-volume-copy/rsync-client:ci
    command:
    - rsync
    args:
    - "-rv"
    - "rsync://user@rsyncd:873/data"
    - "/data"
    env:
    - name: RSYNC_PASSWORD
      value: pass
    volumeMounts:
    - mountPath: /data
      name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: my-pvc
  restartPolicy: Never
